### ISSUE TITLE
install.bash puudused?

### ISSUE THREAD

**Issue by Appii** [iti0201/simulation#1]
Sellejaoks, et install.bash töötaks peab kõigepealt installima pip3 `sudo apt install python3-pip` ja tegema directorid lib `mkdir -p ~/.local/lib/python3.6/site-packages/` ja võibolla directory samamoodi python2.7 kohta.

**Comment by oskarpihlak** [comment]
Panin pull requesti #2

**Comment by GertKanter** [comment]
Merged
